Selenium end-to-end integration test setup
5calls/5calls-old pull request #209
Opened 2017-02-20 03:04 UTC by cdoremus

This PR provides end-to-end (e2e) test configuration and an example e2e test as noted in issue #207. Testing uses ```Selenium``` with ```Mocha``` and ```Chai```.

The example is relatively simple display of the 5calls web application's home page and assertion that the page title is correct. The e2e tests are designed to be run locally. They are best used as a sanity check on significant refactorings such as those suggested in issue #206. The configuration will need to be modified  for Sauce Labs integration.

Documentation on how to run the e2e tests has been added to the Readme fille.

2017-02-27 19:21 UTC, Mr0grog requested changes
Do we need a `_e2e` suffix on all tests here? Seems to me like being in the `e2e` directory should be enough?

Sorry this has taken me some time to get to.

2017-02-27 19:21 UTC, Mr0grog commented on package.json
> +    "e2e": "mocha ./e2e-tests/*.js"
If gulp is our task runner, this should absolutely be managed as a gulp task. It’s OK to have an NPM pass-through, but I don’t think it’s useful—it’s duplicative and doesn’t really add anything. (The exception here are the standardized, particular-to-NPM itself scripts, like `test`, `post-install`, etc.)

2017-02-27 19:21 UTC, Mr0grog commented on e2e-tests/home_e2e.js
> +    return driver.getTitle().then((title)=> {
This test should just return a promise rather than both returning a promise *and* accepting a callback function.

Also, spacing between args and arrow: `(title)=>`

2017-02-27 19:21 UTC, Mr0grog commented on e2e-tests/home_e2e.js
> +  test.beforeEach(() =>{
Spaces in `=>{`

2017-02-27 19:21 UTC, Mr0grog commented on e2e-tests/home_e2e.js
> +});
These `before`/`after` calls should really be either:

- Inside the `describe` block
- In a separate test setup module (like https://github.com/5calls/5calls/blob/master/static/test/setupUnitTests.js for unit tests) since they cover *all* tests, regardless of the file they’re in.

2017-02-27 19:21 UTC, Mr0grog commented on e2e-tests/home_e2e.js
> +          'browserName': 'chrome',
Over-indented by four spaces here?

2017-02-27 19:21 UTC, Mr0grog commented on e2e-tests/home_e2e.js
> +      }).build();
`.build()` should be a new line.

2017-02-27 19:21 UTC, Mr0grog commented on e2e-tests/home_e2e.js
> +const until = webdriver.until;
`By` and `until` are not used.

2017-02-27 22:09 UTC, cdoremus commented on e2e-tests/home_e2e.js
> +      }).build();
Is there an eslint config file that you can attach to this issue so I can pre-lint any of my changes?

2017-02-28 00:15 UTC, Mr0grog commented on e2e-tests/home_e2e.js
> +      }).build();
No, but for this particular issue, the `newline-per-chained-call` rule is probably what you’d want, e.g:

```json
"rules": {
  "no-console": "warn"
}
```

…but I’m not in love with that rule as it can’t really distinguish (or at least didn’t used to) cases like:

```js
// don't want a warning
thing.something().property;
// do want a warning
thing
  .something({
    stuffAcrossManyLines: true
  })
  .property;
```

2017-02-28 22:19 UTC, cdoremus commented on package.json
> +    "e2e": "mocha ./e2e-tests/*.js"
I tried playing with a Gulp task to do this with no luck, so I'll need your help. Sorry, but I haven't worked with Gulp for a while.

2017-02-28 22:30 UTC, cdoremus commented
@Mr0grog I wanted to try out webdriverio because the webdriverjs documentation is sparse, but, according to their docs, webdriverio needs a local selenium standalone server and gekodriver installs. And then you need to run the standalone server separately. This seems like a lot of work for a local e2e test run. There must be an easier way? Please advise.

2017-03-01 00:03 UTC, Mr0grog commented on package.json
> +    "e2e": "mocha ./e2e-tests/*.js"
I think it would just be something like we had before:

```js
// you'll need to bring this require call back, since it got removed when we switched to Karma for unit tests
const mocha = require('gulp-mocha');
...
gulp.task('e2e-test', function () {
  return gulp.src('./e2e-tests/*.js')
    .pipe(mocha({reporter: 'spec'}));
});
```

2017-03-01 00:26 UTC, Mr0grog commented
> according to their docs, webdriverio needs a local selenium standalone server and gekodriver installs. And then you need to run the standalone server separately.

It’s been a while since I’ve tried to use Chromedriver directly with webdriverio, but I thought I remembered it just working. Otherwise, using the `selenium-standalone` service is the easiest way to get selenium running, I think: http://webdriver.io/guide/services/selenium-standalone.html

2017-03-01 00:30 UTC, Mr0grog commented
I don’t want to push over-much on `webdriverio`, though. The `selenium-webdriver` looks much nicer than I remember it being a couple years ago, which is probably the last time I tried using it directly. I don’t know that there’s anything wrong with how you’re using it here and, as you are experiencing, `webdriverio` requires a *lot* more setup.

2017-03-01 03:14 UTC, cdoremus commented on package.json
> +    "e2e": "mocha ./e2e-tests/*.js"
@Mr0grog Thanks. This script worked, but I needed to add some setup so the chromedriver could be found in the PATH.

2017-03-01 03:15 UTC, cdoremus commented on e2e-tests/home_e2e.js
> +const until = webdriver.until;
These have been removed

2017-03-01 03:15 UTC, cdoremus commented on e2e-tests/home_e2e.js
> +          'browserName': 'chrome',
Fixed

2017-03-01 03:16 UTC, cdoremus commented on e2e-tests/home_e2e.js
> +      }).build();
Moved .build() to a new line.

2017-03-01 03:25 UTC, cdoremus commented on e2e-tests/home_e2e.js
> +});
Created a setupEndToEndTests.js file inside of the static/test folder which holds the code that was previously in before() and after().

2017-03-01 03:25 UTC, cdoremus commented on e2e-tests/home_e2e.js
> +  test.beforeEach(() =>{
Fixed

2017-03-01 03:36 UTC, cdoremus commented on e2e-tests/home_e2e.js
> +    return driver.getTitle().then((title)=> {
Without calling done(), the test hangs. I'm not sure how to do what you are asking. Please advise.

Spacing error fixed.

2017-03-01 03:38 UTC, cdoremus commented on package.json
> +    "e2e": "mocha ./e2e-tests/*.js"
Also changed the test name from home_e2e.js to home.js.

2017-03-01 06:21 UTC, Mr0grog commented on e2e-tests/home.js
> +const setup = require('../static/test/setupEndToEndTests');
I kind of feel like code related to these tests should all live inside the `e2e-tests` directory. It’s pretty common to have a `e2e-tests/support/` directory that contains fixtures and setup code or library modules used by multiple tests. At the very least, I don’t think it really makes sense to mix code specific to e2e tests with code specific to unit tests.

(FWIW, the `test` directory is inside `static` instead of at the top level because the backend stuff was also in this repo at the time and I was trying to follow the directory structure that had all front-end-specific stuff in `static`. That placement does feel awkward now.)

2017-03-01 06:49 UTC, Mr0grog commented on e2e-tests/home.js
> +  });
This feels a little verbose and repetitive. If you’re doing this to get at the `driver` object, there might be some nicer options:

- Have an accessor function that returns the current browser driver.
- Use the test context to store it, e.g:

  ```js
  test.before(function() { this.driver = ...; })
  ```

Either of the above would let you simplify these before/after calls to something like:

```js
test.describe('home page', function () {
  // this does the work of `test.before()` and `test.after()`
  setupBrowserTest();

  test.beforeEach(function () {
    this.driver.get(url);
    // or
    getDriver().get(url);
  });
  
  test.it('should show correct page title', function () {
    // test
  });
});
```

Or, as a decorator (kinda fancy):

```js
// `testWithBrowserDriver()` would be kind of like `setupBrowserTest()`
// from above when its return value is called
test.describe('home page', testWithBrowserDriver(() => {
  test.beforeEach(function () {
    this.driver.get(url);
    // or
    getDriver().get(url);
  });

  test.it('should show correct page title', function () {
    // test
  });
}));
```

You could also use Mocha’s `require` option to include setup code instead of using it like a library here (this is kind of what I thought you were going to do), but it might be cleaner that this approach isolates a browser driver instance to a given test suite.

2017-03-01 07:06 UTC, Mr0grog commented on e2e-tests/home_e2e.js
> +    return driver.getTitle().then((title)=> {
If you don’t plan to call `done` and want to return a promise instead, you need to not take `done` as an argument (Mocha checks the number of arguments your function takes and changes behavior based on that). So, either:

```js
test.it('should show correct page title', (done) => {
  let expected = '5 Calls: Make your voice heard';
  // no reason to return this; it doesn't accomplish anything
  driver.getTitle().then((title)=> {
    expect(title).to.equal(expected);
    done();
  });
});
```

OR, what I was suggesting:

```js
// note `done` is not an argument here
test.it('should show correct page title', () => {
  let expected = '5 Calls: Make your voice heard';
  // now you *must* return this promise, as its resolution or
  // rejection is what signals to mocha that the test is done
  return driver.getTitle().then((title)=> {
    expect(title).to.equal(expected);
  });
});
```

There’s also a nice Chai plugin, `chai-as-promised` that gives you some nicer promise-based assertions:

```js
// note again, `done` is not an argument here
test.it('should show correct page title', () => {
  let expected = '5 Calls: Make your voice heard';
  // the `eventually` bit is what chai-as-promised gives you
  // (note again you must return the result of this)
  return expect(driver.getTitle()).to.eventually.equal(expected);
});
```

2017-03-02 18:23 UTC, cdoremus commented on package.json
> +    "e2e": "mocha ./e2e-tests/*.js"
The reason I (and others) like to use npm scripts is because I can be assured that everyone running the scripts are using the same version of gulp (the one in node_modules/.bin). This is particularly important for JS testing because chromedriver, karma and selenium can be very version sensitive.

Also, I don't know about you, but I do not update my global npm modules (like gulp) as often as I should.

2017-03-02 18:28 UTC, cdoremus commented on e2e-tests/home.js
> +const setup = require('../static/test/setupEndToEndTests');
I moved the ```setupEndToEndTests.js``` file into the ```e2e-tests/support``` folder.

2017-03-02 18:48 UTC, cdoremus commented on e2e-tests/home.js
> +  });
I added the ```require``` option to the gulp test:e2e task pointing to ```setupEndToEndTests.js```. I also moved the ```test.before()``` and ```test.after()``` functions into this file.

2017-03-02 20:34 UTC, Mr0grog commented on package.json
> +    "e2e": "mocha ./e2e-tests/*.js"
> I (and others) like to use npm scripts is because I can be assured that everyone running the scripts are using the same version of gulp (the one in node_modules/.bin).

That’s reasonable. I think there are better solutions to this problem (e.g. you should only install `gulp-cli` globally, which delegates to whatever gulp install is in your project), but like I said before, I don’t think it’s *bad* to have NPM pass-throughs. It’s just that there are 16 tasks, and if you really wanted to have npm scripts, you’d wind up having 16 `package.json` lines like:

```
"some-task": "gulp some-task"
```

…which seems kind of repetitive (and error prone) to me. I’m sure I’d make a typo that screws someone else over in at least one of those 16 lines.

> I don't know about you, but I do not update my global npm modules (like gulp) as often as I should.

I just avoid installing anything globally! 😛

Seriously, though, I have found the following in my shell startup script to be *super* useful:

```bash
# Node modules bin
NODE_PATH=./node_modules/.bin
for i in {1..5}
do
  path_level="../$path_level"
  NODE_PATH="$NODE_PATH:${path_level}node_modules/.bin"
done
export PATH="$NODE_PATH:$PATH"
```

…which means any time I run a command, my shell looks first to the closest `node_modules/.bin` directory (up to five levels up in the directory structure). I don’t expect anyone else to be doing that, but it really makes managing tooling dependencies much easier and more reliable.

2017-03-02 20:41 UTC, Mr0grog commented on e2e-tests/support/setupEndToEndTests.js
> + * beforeTests().
These notes about `beforeTests()` and `afterTests()` are no longer relevant, right?

2017-03-02 21:05 UTC, cdoremus commented on e2e-tests/support/setupEndToEndTests.js
> + * beforeTests().
Yes. I'll make the change and push it to Git.

2017-03-02 21:57 UTC, Mr0grog commented on gulpfile.js
> +  return gulp.src(['./e2e-tests/**/*.js'])
I don’t think we want to execute every file in `e2e-tests/support/` as if it was a test, right? I think this needs to be: `['./e2e-tests/**/*.js', '!./e2e-tests/support/**/*.js']`

2017-03-02 22:25 UTC, Mr0grog commented on gulpfile.js
> +      require: 'e2e-tests/support/setupEndToEndTests.js'
This actually isn’t working. It needs to be `./e2e-tests/...` The file is only being run right now by virtue of it being counted as a test (see above).

That said, upon further looking into this, the method used here won’t work at all, so it was bad advice on my part. I’d only used this method to install globals and other helpers for use in tests, not to install setup/teardown handlers on Mocha. It turns out there’s no way to get a handle on the Mocha instance that is going to run the tests here, so it’s infeasible for that use. Sorry :(

Maybe better to include it as the first test file:

```js
return gulp.src([
  './e2e-tests/support/setupEndToEndTests.js',
  './e2e-tests/{*,!(support)/*}.js'
])
  .pipe(mocha({
    reporter: 'spec',
    timeout: 6000
  }));
```

Side note: I had to increase the `timeout` above because fontawesome’s CDN was frequently taking more than the standard 2000 ms allowed for each test. Not sure what’s best here, but so long as the tests will require actual remote resources, we probably need to up it at least a little.

2017-03-03 17:38 UTC, Mr0grog commented
👍

2017-03-03 17:38 UTC, Mr0grog approved these changes

2017-03-04 16:48 UTC, cdoremus commented
@Mr0grog thanks for your help. I learned a lot about configuring and running these tests in the process.

The next step is deciding how we are going to use these tests. My recommendation is to add them to the deploy pipeline rather than being part of every PR check. I suggest this because these tests can be slow and flaky. Still, I am not religious about this opinion, and I invite others to comment.

@nickoneill and @oderby what do you think?

BTW, I have put together a series of other tests for the Home page and added About and FAQ page tests that await merging this PR into master.

2017-03-05 01:58 UTC, oderby commented
Definitely want to hear from @nickoneill on this one, but I'm guessing the deploy pipeline is not yet automated. So while I'd be fine with pushing these tests to run as part of an automated deploy, I'd much rather see these run automatically and in a transparent place (so others can help debug), so they're reliably checking the code. Is there someplace downstream of PRs that these could be run automatically?

Also, @cdoremus have you already seen flakiness with these tests? Or are you just going off of previous experience, when suggesting these will be flaky?

2017-03-05 02:58 UTC, nickoneill commented
You're correct @oderby, there's no automated deployment set up. It's a single-command process at this point, "automated" in the makefile and I don't think there's additional benefit to be gained automating it beyond this at the moment.

I don't know what other part of the process this can be a part of but I could get behind it. Is there a reason it can't run on saucelabs? Do they not support selenium?

This new test run great for me currently. I'd be curious about the general flakiness as well but if it works well I'm happy to make it part of the PR process.

2017-03-05 05:01 UTC, cdoremus commented
@oderby and @nickoneill I started a new branch and put together 5 new tests (for item details, FAQ and About page) and they all run consistently, but it is my (and others) experience that e2e tests can be flaky. This has to do with the nature of these automated requests that are rapidly invoked much faster than a human client could ever do. Our tests pull from the production database, which adds latency to the responses from the automated requests. I have included wait calls in my new e2e tests that stops the test from proceeding until a condition is achieved (e.g. expected page elements or urls are rendered). These wait calls also have a timeout, which I have set to 2 or 3 seconds. They help to minimize flakiness. Still, you could set all the waits to 30 seconds and still have a failing test because the browser is hanging due to client computer, server or network issues.

Adding to the uncertainty is the dynamic nature of the data being sent back by the production server. Ideally, these kind of tests should be run using a dedicated test server and and a consistent test data set.

Despite these caveats, I certainly can sign on to adding these tests as a PR check now. We can always modify the tests or how they fit into the development/deployment pipeline later.

2017-03-05 19:39 UTC, oderby commented
@nickoneill As I understand it ( @Mr0grog and @cdoremus please correct me if I'm wrong) Sauce Labs integration will come next. This first task was just about getting the system set up and configured locally for the project. 

But, that brings up a good point - these can't be run as part of the PR process (or any automated process) until we get Sauce Labs/CI integration set up, right?

2017-03-05 20:42 UTC, Mr0grog commented
> As I understand it ( @Mr0grog and @cdoremus please correct me if I'm wrong) Sauce Labs integration will come next.

That is definitely what I thought the plan was.

> these can't be run as part of the PR process (or any automated process) until we get Sauce Labs/CI integration set up, right?

They can—it’s totally possible to run a browser inside Circle—in fact, I think it has Chrome already available, though it’s not always very up-to-date (most projects have a script to install the latest Chrome as part of their pre-test setup).

I do think these should be PR checks. The whole point of having a massive and reliable CI service is to be able to handle heavy/long builds and tests that are infeasible on your local machine. Even if they’re slow, you still want to run all your tests before merging. You may as well have the CI server do them.

> Ideally, these kind of tests should be run using a dedicated test server and and a consistent test data set.

Totally. Also with local versions of assets that might otherwise come from a CDN (e.g. fontawesome). This PR had gotten into a pretty long back-and-forth, so I was thinking that would probably be better as a second PR.

2017-03-05 20:45 UTC, Mr0grog commented
re: the browser/Circle/Sauce thing: you still ultimately want sauce because you want to test in multiple versions of browsers and across multiple platforms; you only have the OS you’re running on when running a browser directly on Circle. Doing that can be a quick intermediary step to getting Sauce going right.

2017-03-05 21:05 UTC, nickoneill commented
OK, I think we're all on the same page. I'm working on getting a test/staging server up and running, not sure about a consistent data set but at least we'll have some way to deploy new stuff to test without going straight to prod.

Are we good to merge this now or did we need an additional change for this to run by default for PRs? @cdoremus or @Mr0grog, can one of your summarize testing next steps in an issue so we can track going forward.

2017-03-06 02:01 UTC, cdoremus commented
@nickoneill I think this PR is ready to merge. Since the single test in the PR is somewhat of a 'hello world' example, I have some other tests that I've worked on that better exercise an e2e test system. All of these tests can be run manually, and I have included instructions in the ```Readme``` in this PR on how to do that. At the same time we need Sauce Labs and CircleCI configured, which is best done by Rob (@Mr0grog).

Once this PR goes in, I'll close out #207 and open a new one for further discussions. I can also create a new PR containing my new e2e tests if that is agreeable to the group.

2017-03-06 02:19 UTC, nickoneill commented
Perfect, thanks @cdoremus!

2017-03-06 02:19 UTC, merged