Handle local offices without cities
5calls/5calls-old pull request #214
Opened 2017-02-23 05:54 UTC by nickoneill

2017-02-23 07:55 UTC, oderby requested changes
Test?

2017-02-24 06:35 UTC, nickoneill commented
Added a test, my first shot at chai, be gentle @oderby

2017-02-24 09:29 UTC, oderby requested changes
small fix to tests, and nit on (ab)using javascript boolean coercion. Otherwise lgtm!

2017-02-24 09:29 UTC, oderby commented on static/js/components/contact_test.js
> +    expect(content).to.equal(field_offices[0].phone);
This is only testing that when field office data is missing the city, the phone number is still present. You probably also want to check that the state abbreviation is NOT included. Like so:

```javascript
    let content = result.querySelectorAll('ul.call__contact__field-office-list li')[0].textContent;
    expect(content).to.contain(field_offices[0].phone);
    expect(content).to.not.contain(contactData.state);
```

(Note I changed the query selector to not grab just the `a` element, so we can be sure we're checking the entire list item.)

2017-02-24 09:29 UTC, oderby commented on static/js/components/contact_test.js
>      expect(content).to.contain(field_offices[0].city);
We should check that the state is present here.

```javascript
    expect(content).to.contain(contactData.state);
```

2017-02-24 09:29 UTC, oderby commented on static/js/components/contact.js
> +    if (office.city != "") {
no need to compare to empty string. javascript will coerce to boolean based on truthiness of the value, and "" is falsey. So just do `if (office.city)`. This way, you'll also have proper behavior if `office.city===undefined` or `office.city===null`, since those both are falsey. Isn't javascript wonderful??

2017-02-25 03:12 UTC, nickoneill commented
OK! Thanks for the tips, I was wondering about doing some alternate tests and this clears things up.

2017-02-25 03:57 UTC, oderby approved these changes

2017-02-25 04:40 UTC, merged