Adds initial call impact
5calls/5calls-old pull request #229
Opened 2017-03-03 03:29 UTC by bernardwang

## Summary
Fixes issue [#195](https://github.com/5calls/5calls/issues/195)

1. Saves completed calls (not skipped) in localstorage
2. Adds reset functionality
3. Adds initial impact component to ```done.js```, or the completed issue page.

Creates new state variable `userStats`. `userStats.all` is an array of all non-skipped calls, containing `issueid`, `contactid`, and `result`. The other fields for `userStats` are for quick and easy access of call `result`, assuming that information will be displayed in the future.
```
userStats = {
      all: [], 
      contacted: 0,
      vm: 0,
      unavailable: 0,
}
```

The total calls is being displayed on the completed issues page, and only shows the "impact" message if there has been successful calls. Currently, any clicks to "Made Contact", "Unavailable", or "Left Voicemail" are registered in stats, even if the issue is already marked complete.

## Testing
New tests in `stats-test.js` and updated tests in `done-test.js`.

Videos of functionality:
[Does not show impact if no calls were completed](https://i.gyazo.com/e7970cfb33f0d960c36f05434fa85055.mp4)
[Counts successful calls](https://i.gyazo.com/579fe12da99529870cdd4f86ffa0bc72.mp4)
[Stats persist after page refresh](https://i.gyazo.com/9457fe6728fa1265a0165089ffd15dd4.mp4)
[Reset functionality](https://i.gyazo.com/394c32eff279a6c5ef7aeff602b90507.mp4)

## Risks
Many of these decisions were made with assumptions, so much of this is subject to change. Specifically, knowing what stats should be displayed, and where in the UI/UX, would help with this alot! Just let me know what should be changed!

2017-03-03 15:54 UTC, schraj commented
Hi Bernard, Love the videos!  one thing I had run across when playing with the implementation of this myself.  "Your impact is 1 calls" needs to be changed to "Your impact is 1 call".

2017-03-03 20:29 UTC, bernardwang commented
Ah thanks for catching that! Ill fix that soon

2017-03-05 03:08 UTC, nickoneill commented
Awesome @bernardwang! This is exactly the functionality we're looking for. I like the independent contacted/unavail/vm counts too, that could be a fun little personal chart to look at.

I pinged @joshpuckett on slack to see if he has any thoughts on the design, I would definitely like to bring this onto the main page rather than hiding it on done. If he doesn't respond in the next day or so I'll take a crack at it.

2017-03-10 19:33 UTC, oderby commented on static/js/main.js
> +    localStats = {
this should be the default set in line 79, right? What's the point in waiting until here to set it? In the worst case, something could fail in the localStorage code, and we'd never set the default value...

2017-03-10 19:41 UTC, oderby requested changes
While we're waiting for someone from design to take a look at this, here's some comments/feedback.

2017-03-10 19:41 UTC, oderby commented on static/js/main.js
> +localStats = {};
should be `let localStats = {}`

2017-03-10 19:41 UTC, oderby commented on static/js/main.js
> +      defaultStats = {
Could DRY up a bit and move this declaration to line 79, so you'd have

```javascript
let localStats = defaultStats = {
  all: [],
  contacted: 0,
  vm: 0,
  unavailable: 0,
};
```

2017-03-10 19:41 UTC, oderby commented on static/js/components/stats_test.js
> +      result: 'contacted'   // not sure if necessary
Don't think you need the comment here.

2017-03-10 19:41 UTC, oderby commented on static/js/components/stats.js
> +  const userCalls = (state.userStats) ? state.userStats.all.length : 0;
Why the conditional? In main.js you ensure the state is properly initialized.

2017-03-10 19:41 UTC, oderby commented on static/js/components/stats_test.js
> +    expect(result).to.be.defined;
Please check more than just that the view returns something. Ensure the correct number is reported.

2017-03-10 19:41 UTC, oderby commented on static/js/components/stats_test.js
> +});
Per the discussion, please ensure coverage for singular vs pluralization of stats.

2017-03-11 17:41 UTC, bernardwang commented
@oderby thanks for the feedback, I made those changes!

2017-03-11 20:06 UTC, oderby commented on static/js/main.js
> -  if (stats.length > 0) {
I believe you still want this check, just in case something goes wrong with the value stored in localStorage (e.g. the user overrides it, the browser crashes while saving it last, etc.).

2017-03-11 20:09 UTC, oderby commented
Just one comment, then looks good to me.

Regarding design input, I'm not sure what to do. I know @nickoneill is swamped right now, and I'm not certain how the design team typically provides input. I guess you could take a picture of the stats on the 5calls page and post it in #design channel and ask for feedback?

2017-03-19 05:51 UTC, bernardwang commented
Still waiting on design, but I added some tentative updates.

### New Impact page:
![New Impact page](https://cloud.githubusercontent.com/assets/5424713/24078533/054400ce-0c3e-11e7-892f-16fd5693a751.png)

### Updated Done page with link to the Impact page:
![Updated Done page with link to the Impact page](https://cloud.githubusercontent.com/assets/5424713/24078519/ce02f9ee-0c3d-11e7-8260-60f6f8255cb5.png)

### Updated footer:
![Updated footer](https://cloud.githubusercontent.com/assets/5424713/24078527/e5545df4-0c3d-11e7-9b8e-e491c67b2d68.png)

2017-03-21 03:51 UTC, nickoneill commented
This is really good @bernardwang, a few things came up on slack that I'd like to highlight here: 
* capturing the time of a call with the stats, even if we don't surface it at the moment.
* Reporting the call stats as a complete sentence as naomi suggested: "You have *made contact 0 times* and left *0 voicemails*. Your representatives have been unavailable *0 times*"

I don't think we need a huge design to get this on the site. These last things should make this good to merge.

One more thing to think about... some browsers (Safari 9 comes to mind) don't allow localstorage access. Can we hide these entirely if there's no impact so we don't show "your impact is 0 calls" everywhere?

2017-03-22 18:30 UTC, bernardwang commented
Sure thing I can make those changes.

Regarding browsers without localstorage, would we hide the impact page entirely, or just links to it like on the Done page?

2017-03-23 04:06 UTC, nickoneill commented
If there's no impact or no localstorage, just hide the links to impact. I added feedback on the color preferences in slack, this is just about ready to go!

2017-03-23 07:03 UTC, bernardwang commented
Should the link to the Impact page on the bottom nav also be hidden? As of now I only removed the links to the Impact page from the Done page if there is 0 calls.

2017-03-23 22:55 UTC, oderby commented
If we don't have data for impacts, then I don't think any links to impact page should be presented. So yes, in that case also hide the link from the bottom of the nav.

2017-03-24 04:30 UTC, oderby commented on static/js/components/impact.js
> +    <main id="content" role="main" aria-live="polite" class="layout__main" onload=${(e) => send('startup')}>
Why not just add the scrolling to the onload handler? e.g.

```javascript
function load() {
  scrollIntoview();
  send('startup');
}
return html`
  <main ... onload=${load}>
...
```

2017-03-26 05:03 UTC, oderby requested changes

2017-03-26 05:03 UTC, oderby commented on static/html/index.html
> +        <a id="impact__link" href="#impact">
Now that we've removed hash routing, this should just be "/impact"

2017-03-26 05:03 UTC, oderby commented on static/js/main.js
> +let defaultStats = {
nit: this should be a `const`

2017-03-26 05:03 UTC, oderby commented on static/js/components/done.js
> +        <h2>See more stats on <a href="#impact">your impact</a>.</h2>
also needs to be updated to remove hash route

2017-03-26 14:50 UTC, oderby approved these changes
Code changes all look good to me.

2017-03-26 14:52 UTC, oderby commented
@bernardwang there are conflicts with 5calls/master branch that you need to resolve before this can be merged. The CI tests are spurious, so when you push up the rebased branch, we should be good to go.

2017-03-26 16:42 UTC, nickoneill commented
@oderby I'm seeing "no conflicts with base branch" here

2017-03-26 16:57 UTC, oderby commented
@nickoneill are you looking at latest revisions of both branches? Github itself agrees with me. Here's what I see when trying to rebase (included commit shas for reference)

```bash
 ~/code/5calls/web (fa1ec41...) ✔: git rev-parse bernard/track-call
fa1ec418a8d82d875a9d52bda6db10dcdc654b5d
~/code/5calls/web (fa1ec41...) ✔: git rev-parse origin/master
cad1d64449adfcef9f2fbf1f1c284295e4d0c5d7
~/code/5calls/web (fa1ec41...) ✔: git rebase origin/master bernard/track-call 
First, rewinding head to replay your work on top of it...
Applying: Add userStats to localstorage
Using index info to reconstruct a base tree...
M       static/js/components/issues.js
M       static/js/main.js
Falling back to patching base and 3-way merge...
Auto-merging static/js/main.js
CONFLICT (content): Merge conflict in static/js/main.js
Auto-merging static/js/components/issues.js
error: Failed to merge in the changes.
Patch failed at 0001 Add userStats to localstorage
The copy of the patch that failed is found in: .git/rebase-apply/patch

When you have resolved this problem, run "git rebase --continue".
If you prefer to skip this patch, run "git rebase --skip" instead.
To check out the original branch and stop rebasing, run "git rebase --abort".
```

2017-03-26 17:19 UTC, nickoneill commented
Ah yeah, a manual rebase fails. Is there a specific reason we prefer this over a merge which seems like it would succeed (according to github)?

2017-03-26 17:21 UTC, oderby commented
oh, I see. No, squash and merge is fine here.

2017-03-26 17:32 UTC, nickoneill commented
OK, retrying the tests and then I'll pull this in.

2017-03-26 17:35 UTC, merged

2017-03-26 17:38 UTC, nickoneill commented
This is fantastic @bernardwang! Thanks for keeping up with the unusually long review process for this one.