Fix #247
5calls/5calls-old pull request #250
Opened 2017-03-16 19:44 UTC by bernardwang

##Summary
[#247](https://github.com/5calls/5calls/issues/247)
Not sure if this is the best way to do it, but it is very fast.

2017-03-16 23:18 UTC, schraj approved these changes
This looks correct to me.

2017-03-21 01:09 UTC, cdoremus requested changes
I tried running your 247-pr branch locally and you are missing the 'raf' dependency in package.json which causes the gulp build to fail.
Also, the 247-pr branch is based on your master branch, which you created (and changed) in PR #226. It -- and any other PR -- should be based on an up-to-date master branch refreshed from 5calls/5calls. To do this, add a remote branch to your fork pointing to the 5calls/5calls repo and use that branch to refresh your master branch before you create a branch for your PR. Since this is a small change, I'll let this issue go this time, but please use the proper procedure for any new PR. Thanks.

2017-03-22 17:15 UTC, bernardwang commented
@cdoremus I see, next time I will follow that procedure. I incorporated the small changes from , [#249](https://github.com/5calls/5calls/pull/249) but this PR is quite messy, would it be better to close it and redo it properly?

2017-03-23 04:08 UTC, nickoneill commented
Nah, we can squash those commits into a single one for clarity. Make sure to use that option when this is ready to merge @cdoremus

2017-03-23 07:00 UTC, bernardwang commented
Ok, let me know if theres anything else I should do for this PR. I believe this will need to be merged before [#229](https://github.com/5calls/5calls/pull/229).

2017-03-23 19:28 UTC, oderby commented on static/js/components/issues.js
> -const scrollIntoView = require('scroll-into-view');
Can we now remove the dependency on `scroll-into-view` from package.json now? (Assuming this is the last use of it, and we don't re-break everything again, i.e. #255 ?)

2017-03-23 19:55 UTC, oderby commented
Latest set of changes looks good to me - @cdoremus any objections to merging?

2017-03-23 20:54 UTC, cdoremus commented
@bernardwang @oderby I noticed that when you click on the About link in the footer that the page doesn't scroll to the top. It would be nice to fix that in this PR. Any objections?

2017-03-23 22:11 UTC, oderby commented
If @bernardwang thinks it's an easy fix and can get it up soon, then fine by me.

2017-03-24 03:20 UTC, bernardwang commented
I didn't find any more instances of `scroll-into-view` when I searched in the project, so it _should_ be safe to remove.

The footer links are just ordinary links, so I added an event listener to attach scrolling. It's easy, but perhaps a bit sloppy. Maybe in the future the footer could be a component rather than being hardcoded in `index.html`? Open to any other suggestions!

2017-03-24 04:26 UTC, oderby commented
Yeah, when I agreed with @cdoremus I didn't realize the footer wasn't part of a component. Also, in #251 (wip on i18n support) they are already doing some work to pull the footer into it's own component. Given both of these facts (which make fixing it now rather difficult/ugly, as you point out), I'm actually no longer in favor of increasing the scope of this PR to fix scrolling to top of about page. Sorry for flip-flopping here...

2017-03-24 18:17 UTC, cdoremus commented
@bernardwang I agree with @oderby that we should hold off on the About link scrolling for now.

2017-03-24 20:15 UTC, bernardwang commented
@oderby What about this option from [#229](https://github.com/5calls/5calls/pull/229#pullrequestreview-28828338)?

2017-03-24 21:39 UTC, oderby commented
Seems fine to me. Pulled it down and it seems to work fine @cdoremus thoughts?

Also, @bernardwang this doesn't rebase cleanly onto master branch, due to recent changes - can you merge master and resolve those conflicts and push them up? Don't worry about the mess of the history - as @nickoneill said above, we'll squash when merging this PR in, so it'll get all cleaned up.

2017-03-24 23:27 UTC, bernardwang commented
I pulled, but didn't seem to get any conflicts. Is this ok?
I should probably rebase more in the future haha, this history is pretty bad

2017-03-25 17:53 UTC, cdoremus approved these changes
Looks good! Thanks for you patience with our reviews. All commits will be squashed when the merge is done.

2017-03-25 17:53 UTC, merged

2017-03-25 18:11 UTC, nickoneill commented
Thanks @bernardwang! This fixes some issues needed for #256 as well, much appreciated!