I18n - Draft of Localization
5calls/5calls-old pull request #251
Opened 2017-03-16 22:45 UTC by schraj

1. This uses the i18Next localization package.
2. It uses the i18next-xhr-backend package to load the locale files from the server when requested. It does this once it finds the users browserLanguage. Therefore, I've wrapped the "startApp" function in the callback from the initialization process for the i18n cache. Otherwise, it will not have the localized resources as it is starting up.
3. If there is html in the localized string(and this is also the default), it wraps the localized string in a span tag (configurable, can also request a div tag) and then builds it into dom nodes using "DOMParser" or a polyfill so that choo can consume it when passed to the choo template literal as variable. If you set an argument that you want "justText" it will skip this step and just do the localization.  Because I am now using this slightly more expensive method of transforming the string for choo consumption, it might make sense to identify strings that must be "JustText" and these could be passed with the "justText" parameter set to true so that they can be handled without a dom translation step.
4. The footer that is on the Index.html page is not handled as a choo widget and so I had to handle it differently. You'll see that I set the localized values on it manually after the i18n cache is initialized. If we moved the footer to a choo widget, this would be cleaner. However, it would require a little structural markup change.
5. The privacy.html page is not done. We can talk about it once we evaluate the rest of this. It is also not a choo widget so would need different handling like the footer.
6. The main code for the localization is in /js/utils/translation.js
7. The tests and some usage hints are in translation_tests.js
8. The locale files are in /locales/. I made a very naive spanish translation file just for tests. It will have to be redone by a real translator.
10. There is a new gulp task called "test:windows" that I'm just using to get karma to work on windows and not planning to merge as part of this localization work.

2017-03-17 16:50 UTC, beausmith commented on static/html/index.html
> +    <script>
It'd probably be better to make components for any text strings in this file so that `${t.getText("foo")}` can be used. This DOM search/replace implementation is too fragile.

2017-03-17 17:25 UTC, schraj commented
Note that there will need to be some coordination with the backend when the localization of the issues is implemented.  This does not look at this yet.  
The following items will need addressed:
1) What locales is the backend currently supporting? Just a simple api call from the backend returning an array of supported locales.
2) The frontend will need to pass the supported locale that it wants the issues returned in from the backend.
3)  The frontend will need to take the localized issue and pass it through the renderer(in translation.js) to make it consumable by choo(if we want to support html in issues, currently this is not happening in issues-html not being put into them).

2017-03-17 17:42 UTC, schraj commented on static/html/index.html
> +    <script>
Yeah, I agree with that.  It looks like all but the footer is replaced immediately upon app startup.  That "Main" part of the page seems to be there in case the app is broken.  If broken, the translation won't work either.

At the bottom it has this:
<h2 class="callcount">5 Calls will be right back.</h2>

I do have a version that pulls out the footer into a component.  That is a pretty straightforward change that requires some structural markup change.  I didn't add that to this because I wanted to minimize the impact of this one change.  However, I agree that it would be the better way to go and it is an easy thing to do.

2017-03-17 20:44 UTC, schraj commented on static/html/index.html
> +    <script>
@beausmith Since this is the first thing that jumped out at you, I think I'll go ahead and merge in my other version that has the footer as a component.  Might as well do it the right way all at once.

2017-03-17 21:08 UTC, schraj commented
@beausmith I added in the footer component(removed it from Index.html) so that it can be localized like the rest of the site.

2017-03-21 07:27 UTC, beausmith reviewed
Fantastic work @schraj! This looks solid. 🇺🇸 :handshake: 🇲🇽 

Just a few nits/suggestions.

One wish-list (aka scope creep) thought: It would ease the translation process for translators if prose (multiple paragraphs of text) on the About, Hypothesis, etc pages be contained in a single translation key. Often this prose doesn't always map 1:1… there may be need for additional paragraph, or a different list of articles, etc. I was excited for the markdown option because this would be supported. But this is not critical for this PR. 

One other nit: I wish that the translation methods were simply `${t('key')}` without the `getText` part. If the logic to get the browser locale was place in it's own utils file… 😃

2017-03-21 07:27 UTC, beausmith commented on static/js/components/outcomes.js
> +  //const callsPluralization = contactsLeft > 1 ? "people" : "person";
nit: delete dead code.

2017-03-21 07:27 UTC, beausmith commented on static/js/components/outcomes.js
> +  const contactsLeftText =  t.getText("outcomes.contactsLeft", { "contactsRemaining": contactsLeft}); //contactsLeft + " more " + callsPluralization +" to call for this issue.";
nit: delete dead code comment.

2017-03-21 07:27 UTC, beausmith commented on static/js/utils/translation.js
> +        useDiv = useDiv || false;
```diff
+    getText : (key, variableObject = {}, justText = false, useDiv = false) => {
-    getText : (key, variableObject, justText, useDiv) => {
-        variableObject = variableObject || {};
-        justText = justText || false;
-        useDiv = useDiv || false;
```

2017-03-22 01:43 UTC, cdoremus commented
Please make sure this code does not have any linting warnings or errors by rebasing against the latest master and running `gulp eslint`. The latest PR merged into master (#244) fixed all undefined and unused variable lint violations.

2017-03-22 18:01 UTC, beausmith commented
@schraj - shower thought… the ability for the content team to markup the issue text using Markdown would be the simplest way to allow them to add basic formatting.

2017-03-24 01:17 UTC, oderby requested changes
Left some comments. I'm definitely jumping in and missing some of the context from the previous iterations, so apologies if I'm asking something you've already addressed/resolved.

Also, I would second @beausmith request that it be just `${t('key')}` (as a small nit)

2017-03-24 01:17 UTC, oderby commented on static/html/index.html
>        <aside id="nav" role="contentinfo" class="layout__side">
please fix up indenting.

2017-03-24 01:17 UTC, oderby commented on static/html/index.html
> +          <label for="email" id="footer-emailLabel">Get email alerts once a week</label>
I'm not seeing how these ids are used? Why are these added ids needed?

2017-03-24 01:17 UTC, oderby commented on static/locales/es.json
> +        "article1":"<a href='https://www.nytimes.com/2016/11/22/us/politics/heres-why-you-should-call-not-email-your-legislators.html'>'Here’s Why You Should Call, Not Email, Your Legislators'</a> <s
Why aren't the link texts translated?

2017-03-24 01:17 UTC, oderby commented on static/js/components/about.js
> +      <p>${t.getText("about.whoIs5Calls.broughtToYouBy")}
Looks like we lost a bunch of the contributors listed here?

2017-03-24 01:17 UTC, oderby commented on static/js/components/call.js
> +        <p class="call__text">${t.getText('call.reason', { contactEmail: constants.contact.email})}</p>
I find the key `call.reason` here to be a bit misleading - it's the key for the reason why there is no calls to make. Perhaps a better key would be `noCalls.reason`? (Then also would change `call.title` -> `noCalls.title` and `call.nextStep` -> `noCalls.nextStep`)

2017-03-24 01:17 UTC, oderby commented on static/js/components/callcount.js
> +  function callCount(state) {
(perhaps for future work) Would it make sense to move this into the [`interpolation.format` option](http://i18next.com/translate/formatting/)? Right now, this is the only place we expect to have numbers >999, but eventually we might see them somewhere else. Something like the following is what I'm thinking.

```javascript
interpolation: {
  format: function(value, format, lng) {
    if (value instanceof Number) {
      // Number.toLocaleString() doesn't work on Safari 9 (see https://github.com/5calls/5calls/issues/197)
      if (window.Intl && typeof Intl.NumberFormat == 'function') {
        return value.toLocaleString();
      } else {
        // As a fallback, use a quick-and-dirty regex to insert commas.
        // When in doubt, get code from stackoverflow: http://stackoverflow.com/a/2901298/7542666
        return value.toString().replace(/\B(?=(\d{3})+(?!\d))/g, ",");
      }
    }
    return value;
  }
}

2017-03-24 01:17 UTC, oderby commented on static/js/components/hypothesis.js
>          <li><a href="https://itunes.apple.com/us/app/5-calls/id1202558609?mt=8"><img class="ios" src="/img/app-store.svg" alt="5 Calls on the App Store" /></a></li>
Should we care about translating alt-texts?

2017-03-24 01:17 UTC, oderby commented on static/js/components/issues.js
> +    return debug ? html`<a href="#" onclick=${resetCompletedIssues}>${t.getText("common.reset")}</a>` : html``;
do we really expect devs to be debugging who need es support?

2017-03-24 01:17 UTC, oderby commented on static/locales/en.json
> +      "getApp": "Get the 5 Calls app:"
Should be `"Get the $t(common.5Calls) app:"`

2017-03-24 01:17 UTC, oderby commented on static/js/utils/translation.js
> +    //              Note: if the third parameter is false, this fourth parameter will be ignored because the text will not be wrapped at all.
I think you mean "...third parameter is **true**..."

2017-03-24 01:17 UTC, oderby commented on static/locales/en.json
> +      "enterYourLocation":"<a id='lnkEnterAddress'>Enter your address</a> to identify your representative in the House.",
Can we pass the id to use for the anchor as an interpolated value? e.g. `... <a id='{{anchorId}}'> ...`. This would avoid unnecessary coupling between the code and the translation files.

2017-03-24 01:17 UTC, oderby commented on static/locales/en.json
> +      "enterYourLocation":"<a id='lnkEnterAddress'>Enter your address</a> to identify your representative in the House.",
Alternatively, can we pass in a reference to the function as an interpolation, and leave it as an onclick handler? Or does interpolation only work with strings and numbers?

2017-03-24 01:17 UTC, oderby commented on static/js/utils/translation.js
> +        useDiv = useDiv || false;
Agreed, but this has a subtlety that if we switch to this, will need to change all the places in the current version of code where we call `t.getText(key, null, true)` to `t.getText(key, undefined, true)` in order to trigger the default value for `variableObject`.

2017-03-24 01:17 UTC, oderby commented on static/js/utils/domParser.js
> +/*
Can you add a comment on what this monkeypatch is doing and why we need it?

2017-03-24 01:17 UTC, oderby commented on static/js/utils/translation_test.js
> +    it('should return the phrase in a "span" tag when third argument to getText() is missing', () => {
I think you mean "...when third argument...is false"

2017-03-24 01:17 UTC, oderby commented on static/js/utils/translation_test.js
> +    it('should return the localized phrase in a span when no interpolation or pluraliation arguments are passed in the second, or options, argument', () => {
(test aesthetic nit) I think the tests should be structured as follows:

```javascript
describe('translation')
  describe('getText')
    describe('arguments')
    describe('simple localization')
    describe('pluralization and interpolation')
  describe('getLocaleFromBrowserLanguage')
```

2017-03-24 01:17 UTC, oderby commented on static/js/utils/translation_test.js
> +    it('with an undefined argument, should get "en" locale', () => {
Please stick with standard format of "should [result] when [scenario]" for test cases.

2017-03-24 01:17 UTC, oderby commented on static/test/setupUnitTests.js
> +    // There are some tests specific to localization where we reload the cache with another locale, at that point we re-initialize
Did you add any tests which use a different locale? I didn't notice any...

2017-03-24 01:17 UTC, oderby commented on static/js/utils/translation.js
> +    getLocaleFromBrowserLanguage : (browserLanguage) => {
Did you look at using the language detector i18next provides, [i18next-browser-languageDetector](https://github.com/i18next/i18next-browser-languageDetector)?

2017-03-24 01:17 UTC, oderby commented on static/js/main.js
> +}, () => {
can't this just be `init(options, startApp)` instead of `init(options, () => { startApp();})` ?

2017-03-24 01:34 UTC, oderby commented
Another thing that you'll need backend support for is routing to fetch the locale files (it *just works* on localhost because gulp is actually running a local static file server, but without backend changes it won't work on prod)

2017-03-24 01:48 UTC, oderby commented on static/locales/en.json
> +      "busyLine": "Busy Line",
Should be "Busy Line?" (missing question mark)

2017-03-24 01:57 UTC, oderby commented on gulpfile.js
>  gulp.task('deploy', ['html', 'sass', 'build-scripts', 'extra', 'copy-images']);
Also need to add `'locales'` task as a part of the deploy task.

2017-03-25 21:27 UTC, schraj commented on static/html/index.html
> +          <label for="email" id="footer-emailLabel">Get email alerts once a week</label>
good catch.  was from an earlier iteration.  I'll remove them.

2017-03-25 21:29 UTC, schraj commented on static/js/components/about.js
> +      <p>${t.getText("about.whoIs5Calls.broughtToYouBy")}
May have been from a early iteration where I was trying things out.  I'll get the latest.

2017-03-25 21:30 UTC, schraj commented on static/js/components/callcount.js
> +  function callCount(state) {
Yes, great point.  I had considered this but didn't want to increase the scope of this already large change.

2017-03-25 21:31 UTC, schraj commented on static/js/components/issues.js
> +    return debug ? html`<a href="#" onclick=${resetCompletedIssues}>${t.getText("common.reset")}</a>` : html``;
probably not, but was just a single item, so seemed a harmless piece of syntactic sugar.  However, if all dev work is discussed in english this is definitely not needed.  Will remove it.

2017-03-25 21:33 UTC, schraj commented on static/locales/en.json
> +      "enterYourLocation":"<a id='lnkEnterAddress'>Enter your address</a> to identify your representative in the House.",
We can definititely do the first(pass the id).  I was not able to get it to recognize a function.  I'll look again, and do the first suggestion as a fallback option.

2017-03-26 21:25 UTC, schraj commented on static/locales/en.json
> +      "getApp": "Get the 5 Calls app:"
done

2017-03-26 21:25 UTC, schraj commented on static/js/utils/translation.js
> +    //              Note: if the third parameter is false, this fourth parameter will be ignored because the text will not be wrapped at all.
done

2017-03-26 21:28 UTC, schraj commented on static/js/components/issues.js
> +    return debug ? html`<a href="#" onclick=${resetCompletedIssues}>${t.getText("common.reset")}</a>` : html``;
done

2017-03-26 21:34 UTC, schraj commented on static/js/components/hypothesis.js
>          <li><a href="https://itunes.apple.com/us/app/5-calls/id1202558609?mt=8"><img class="ios" src="/img/app-store.svg" alt="5 Calls on the App Store" /></a></li>
yes, i think we should.  added them.

2017-03-26 21:37 UTC, schraj commented on static/js/components/call.js
> +        <p class="call__text">${t.getText('call.reason', { contactEmail: constants.contact.email})}</p>
makes sense. changed.

2017-03-26 22:06 UTC, schraj commented on static/js/components/about.js
> +      <p>${t.getText("about.whoIs5Calls.broughtToYouBy")}
fixed.

2017-03-26 22:08 UTC, schraj commented on static/locales/es.json
> +        "article1":"<a href='https://www.nytimes.com/2016/11/22/us/politics/heres-why-you-should-call-not-email-your-legislators.html'>'Here’s Why You Should Call, Not Email, Your Legislators'</a> <s
I was thinking these might be different articles per language because as it is, they will point to english language articles.  For now, I'll translate the links.

2017-03-26 22:11 UTC, schraj commented on static/locales/es.json
> +        "article1":"<a href='https://www.nytimes.com/2016/11/22/us/politics/heres-why-you-should-call-not-email-your-legislators.html'>'Here’s Why You Should Call, Not Email, Your Legislators'</a> <s
fixed.

2017-03-26 23:31 UTC, schraj commented
@beausmith @oderby  I've made some interim fixes but not ready for another review yet.  Will let you both know.

2017-03-27 02:58 UTC, schraj commented on gulpfile.js
>  gulp.task('deploy', ['html', 'sass', 'build-scripts', 'extra', 'copy-images']);
done

2017-03-27 02:58 UTC, schraj commented on static/js/components/outcomes.js
> +  //const callsPluralization = contactsLeft > 1 ? "people" : "person";
done

2017-03-27 02:59 UTC, schraj commented on static/js/components/outcomes.js
> +  const contactsLeftText =  t.getText("outcomes.contactsLeft", { "contactsRemaining": contactsLeft}); //contactsLeft + " more " + callsPluralization +" to call for this issue.";
done

2017-03-27 03:01 UTC, schraj commented on static/html/index.html
>        <aside id="nav" role="contentinfo" class="layout__side">
done

2017-03-27 03:01 UTC, schraj commented on static/html/index.html
> +          <label for="email" id="footer-emailLabel">Get email alerts once a week</label>
done

2017-03-27 03:41 UTC, schraj commented on static/js/components/outcomes.js
> +  //const callsPluralization = contactsLeft > 1 ? "people" : "person";
removed the t.getText(...) and now it is just t.('key')

2017-03-27 04:24 UTC, schraj commented on static/js/utils/translation.js
> +    getLocaleFromBrowserLanguage : (browserLanguage) => {
yes, I looked at it but we have the issue of having to check with the backend to see also what it will support before choosing what language to use.  That means we would have to write a "custom detector" that plugs into their detection framework.  We essentially end up doing it ourselves anyway. I have now added the use of local storage to cache the locale so we don't look it up each time.

2017-03-27 04:29 UTC, schraj commented on static/js/utils/translation_test.js
> +    it('should return the localized phrase in a span when no interpolation or pluraliation arguments are passed in the second, or options, argument', () => {
done

2017-03-27 04:31 UTC, schraj commented on static/js/utils/translation_test.js
> +    it('should return the phrase in a "span" tag when third argument to getText() is missing', () => {
fixed

2017-03-27 04:36 UTC, schraj commented on static/js/utils/translation_test.js
> +    it('with an undefined argument, should get "en" locale', () => {
fixed

2017-03-27 04:36 UTC, schraj commented on static/js/main.js
> +}, () => {
yep, good point. fixed.

2017-03-27 04:36 UTC, schraj commented on static/locales/en.json
> +      "busyLine": "Busy Line",
fixed

2017-03-27 06:15 UTC, beausmith commented
Thanks for all the changes @schraj. I know it's quite a bit of work. Can't wait to see this get merged.

2017-03-27 18:58 UTC, schraj commented on static/js/utils/domParser.js
> +/*
I've removed the monkeypatch.  It was for supporting older browsers(IE10), but I misread the compatibility chart and IE10 is supported without the patch.  It looks like the rest of the browsers should be current enough with respect to this functionality.

2017-03-27 20:31 UTC, schraj commented on static/test/setupUnitTests.js
> +    // There are some tests specific to localization where we reload the cache with another locale, at that point we re-initialize
added.

2017-03-29 04:47 UTC, schraj commented
@greggraf Have you seen this type of error on Circle CI before?  The first several of the browsers work correctly and the tests pass and then these three give the following errors.  You can see the full logs by going into the last 15 or so failed builds.  

`Safari 10.0.1 (Mac OS X 10.12.1) ERROR
  Disconnected, because no message in 30000 ms.
29 03 2017 04:41:59.801:ERROR [reporter.sauce]: ✖ Test Disconnected
29 03 2017 04:42:06.217:WARN [Edge 14.14393.0 (Windows 10 0.0.0)]: Disconnected (1 times), because no message in 30000 ms.
Edge 14.14393.0 (Windows 10 0.0.0) ERROR
  Disconnected, because no message in 30000 ms.
29 03 2017 04:42:06.220:ERROR [reporter.sauce]: ✖ Test Disconnected
29 03 2017 04:42:07.464:WARN [Safari 9.1.2 (Mac OS X 10.11.6)]: Disconnected (1 times), because no message in 30000 ms.
Safari 9.1.2 (Mac OS X 10.11.6) ERROR
  Disconnected, because no message in 30000 ms.
29 03 2017 04:42:07.465:ERROR [reporter.sauce]: ✖ Test Disconnected`

I've been pulling out my changes that went in since this started happening, but can't pinpoint what is causing it.  Also, is there a way to get more detailed logs from the failing VMs?

2017-03-29 12:09 UTC, greggraf commented
@schraj - I have not seen this error before. I ran the tests locally on Safari and had no problem. I think the next move to troubleshoot would be to see if SauceLabs has any clues, but that means getting access to the account. I think @nickoneill has access, maybe @cdoremus. It seems like the browsers are hanging, but its strange that its only these.

2017-03-29 15:32 UTC, schraj commented
@greggraf Thanks greg, First I'll try rolling back my commits to the point where it passed and start adding them back in one by one.  If that doesn't work, I'll start digging into the saucelabs info further.

2017-03-30 15:37 UTC, schraj commented
Even after rolling back changes to a point at which this pullrequest was passing the CI tests, the ci run is now failing while providing no information.  

I'm going to close this pull request and open a new one. I'll then add in the changes progressively to see if I can identify where the ci error begins happening.

2017-03-31 01:05 UTC, schraj commented
I'm reopening this pull request to test it with @oderby fix.

2017-03-31 07:48 UTC, oderby requested changes

2017-03-31 07:48 UTC, oderby commented on static/html/index.html
> +          <i class="fa fa-github" aria-hidden="true"></i> openSource
Probably should stay "Open Source"

2017-03-31 07:48 UTC, oderby commented on static/js/components/noContact.js
> +  function initializeFragment(targetId) {
Perhaps a better name would be `initializeLocalizedAnchors`?

2017-03-31 07:48 UTC, oderby commented on static/js/components/noContact.js
> +      const targetId = 'lnkSetYourLocation';
Now that I look at this again, is there any reason we need to give them both a unique id? Instead, we could use a single unique class name for both of them, put a single onload callback on the top level div for this component (line 22/32 below), and use `document.getElementsByClassName` in `initializeFragments` above. Not a big deal either way, just removes some complexity here.

2017-03-31 07:48 UTC, oderby commented on static/js/main.js
> +    const cachedUserLocale = userLocaleDetection(navigator.language || navigator.userLanguage);
remove `const` here - you already declared the variable in the `let` statement on line 81

2017-03-31 07:48 UTC, oderby commented on static/js/main.js
> -      const viaParameter = window.location.host === '5calls.org' ? 'web' : 'test';
did you mean to remove this?

2017-03-31 07:48 UTC, oderby commented on static/js/utils/localization.js
> +    start: (cachedUserLocale, cb) => {
nit: rename `cachedUserLocale` to just `userLocale` or such - doesn't matter here if it's cached or not.

2017-03-31 07:48 UTC, oderby commented on static/js/utils/translation.js
> +/*key - the localization key in the locale file
can you fix up the indentation here? And also use the more standard format for block comments:
```javascript
  /**
   * this is a block comment. 
   * wheee
   */
```

2017-03-31 07:48 UTC, oderby commented on static/js/utils/userLocaleDetection.js
> +// Get the user's locale.
Is there a reason this file can't be merged into utils/localization.js?

2017-03-31 07:48 UTC, oderby commented on static/test/setupUnitTests.js
> +    'debug': false,
Did you mean to check this in?

2017-03-31 07:48 UTC, oderby commented on static/js/utils/localization.js
> +            //'debug': true,
nit: remove dead code

2017-03-31 07:48 UTC, oderby commented on static/js/utils/translation_test.js
> +          i18n.changeLanguage('en', () => {
You can put this in an [`afterEach` hook](https://mochajs.org/#hooks) within just this suite (so insert it at line 91).

2017-03-31 07:48 UTC, oderby commented on static/js/utils/translation_test.js
> +        i18n.changeLanguage('es', () => {
Shouldn't this be `'es-mx'`? Or something other than `'es'` - right now it's identical test to the one above.

2017-03-31 18:56 UTC, schraj commented on static/js/components/noContact.js
> +      const targetId = 'lnkSetYourLocation';
good point. changed.

2017-03-31 19:36 UTC, schraj commented
@oderby  Thanks for the great reviews.  With such a big change, your reviews have been essential. I believe I've now addressed all of the items.  

The final items to consider:
1) Coordination with the backend
2) A close look over the running site by another set of eyes, preferably content person?  With so many changes, seem likely that small text changes might have slipped through.

2017-04-04 00:07 UTC, Mr0grog commented on gulpfile.js
> +});
Apologies for the drive-by comment here, but is this still needed now that #272 was merged?

2017-04-04 08:47 UTC, oderby reviewed
Took a more detailed pass at the site running with your changes, overall looks good, but found a few small things to address (also, @Mr0grog comment needs addressing as well).

Also, I'm not sure what changes you think are needed on the backend. This PR works when I run it against the backend locally.

Beyond that, here's the followon/remaining work to be done before this should be merged:
- [ ] address review comments
- [ ] Do another merge from master (if needed)
- [ ] create issue to localize FAQ page
- [ ] create issue to localize Privacy page (?)
- [ ] Post in #i18n channel to get help/review for en.json strings (probably easiest just to upload both files and ask for a review)
- [ ] Probably a good idea to get someone else to take another look over entire page and copy, making sure we didn't miss any copy changes that landed since you started this PR.
- [ ] Someone should look over the site in spanish (perhaps after you get the translations reviewed) to make sure it all fits together logically.

2017-04-04 08:47 UTC, oderby commented on static/js/components/noContact.js
> +    let els = document.getElementsByClassName(`${targetClassName}`);
Why the interpolation here? Couldn't it just be `document.getElementsByClassName(targetClassName);`?

2017-04-04 08:47 UTC, oderby commented on static/js/components/impactResult.js
> +  // Jeremy- TODO, when bernard has finalized his styling, need to handle clash with styling of span because I'm
impact code (#229) has merged (with a small copy update in #142) - Can you please pull in that copy change (just merge master again) and then can we fully resolve this TODO?

In particular, on the latest master, only part of the callSummaryText is bolded:
![image](https://cloud.githubusercontent.com/assets/1351158/24645860/ac454b70-18ce-11e7-8fe2-fc69f0ac9a49.png)

2017-04-04 08:47 UTC, oderby commented on static/js/main.js
> +let startApp = () => {
So technically, this cb will receive an error, if one occurs, from loading the locale file from the server (due to server being broken or just network hiccup) - we may want to do something other than blindly loading the app in such a case. Otherwise, we get something that looks like:
![image](https://cloud.githubusercontent.com/assets/1351158/24647047/100a9652-18d3-11e7-9b89-08564811d146.png)
For now, I propose that in such a case (`err !== undefined`), we do not start the app, falling back on the base index.html. And then file a new issue to investigate improving the behavior of the app if we fail to load the locale files.

2017-04-04 08:47 UTC, oderby commented on static/js/constants.js
> +    loadPath: 'locales/{{lng}}.json'
This needs to be `loadPath: '/locales/{{lng}}.json'` in order to ensure we always load from the root of the server, not relative to current url (otherwise, if you refreshed when on url /issue/#issueid, it would try to load the locales from /issue/locales/en.json...

2017-04-04 08:47 UTC, oderby commented on static/locales/en.json
> +      "chooseALocation": "Choose a location",
Why did this copy change? On [current master](https://github.com/5calls/5calls/blob/master/static/js/components/issuesLocation.js), the text is "Enter and address or zip code" and has been that way for 2 months...

2017-04-04 08:47 UTC, oderby commented on gulpfile.js
> -
Looks like you dropped commit [39af7ec7](https://github.com/5calls/5calls/commit/39af7ec757918ed01e0cb3403aa43a3353642a2f#diff-b9e12334e9eafd8341a6107dd98510c9) when resolving merge conflicts. Please add it back in.

2017-04-04 08:47 UTC, oderby commented on static/html/index.html
> -  <head>
Are you making any intentional, substantive changes to this file? If not, I'd prefer you make whitespace changes (if you really care so much) in a different commit, just to keep this commit a little clearer.

2017-04-04 08:47 UTC, oderby commented on .eslintignore
> +coverage/*
Can you drop this whitespace change from your commit?

2017-04-04 15:15 UTC, schraj commented
Thanks @oderby.  I'll make those fixes in the next day or so.

The one issue that this PR will have without coordination with the backend is if the user's browser  locale is "es"(spanish").  In that case, the site will be in Spanish(using my bad Spanish translation) and the Issues will be in English.

For a solution, and maybe this is what you are thinking, I could set the supported locales to be just "en"(English).  Then, it would always just fall back to that. That way, we could get the PR merged and then handle coordination with the backend and issues next.

2017-04-04 15:45 UTC, schraj commented on static/js/constants.js
> +    loadPath: 'locales/{{lng}}.json'
done

2017-04-04 15:46 UTC, schraj commented on static/js/main.js
> +let startApp = () => {
when I try the err!==undefined, that itself throws an error. 

However, when I throw an error from within localization.start or the callback, I get the fallback index.html page as desired.  How, exactly, are you getting the result you are showing?

2017-04-04 15:50 UTC, schraj commented on static/locales/en.json
> +      "chooseALocation": "Choose a location",
I'm just using the wrong key. fixed.

2017-04-04 15:57 UTC, schraj commented on gulpfile.js
> -
nice catch. done

2017-04-04 16:05 UTC, oderby commented on static/js/main.js
> +let startApp = () => {
huh? You've declared `err` as an argument, right? e.g.

```javascript
let startApp = (err) => {  
  // If we errored on initializing localization, then we won't have the
  // right content for most of the app. For now, just fallback to the default index.html in that case.
  if (err !== undefined) {
    return;
  }
  const tree = app.start();
  ...
```

2017-04-04 16:11 UTC, schraj commented on static/js/main.js
> +let startApp = () => {
ah, gotcha.  thought you were looking for something global.  you are thinking of specifically a localization failure.  good point.

2017-04-04 16:17 UTC, oderby commented
@schraj let's definitely see if we can't get you some help on reviewing the translations from i18n channel - it might take a while, so the sooner we get the request up there, the better.

Regarding spanish site with english issues: my understanding from @nickoneill was that was perfectly fine. It's what we're doing in the apps and will be the case until we can coordinate/support spanish issues.

2017-04-04 16:21 UTC, schraj commented on static/js/components/impactResult.js
> +  // Jeremy- TODO, when bernard has finalized his styling, need to handle clash with styling of span because I'm
fixed

2017-04-04 19:56 UTC, schraj commented
@oderby I've done everything on the checklist except these two:

- Probably a good idea to get someone else to take another look over entire page and copy, making sure we didn't miss any copy changes that landed since you started this PR.

- Someone should look over the site in spanish (perhaps after you get the translations reviewed) to make sure it all fits together logically.

2017-04-06 04:28 UTC, nickoneill commented
Excited to get this in! I'll take it for a spin in the next few days.

2017-04-06 07:09 UTC, oderby requested changes
two things lost/missed in the back and forth, then it seems good to me.

2017-04-06 07:09 UTC, oderby commented on gulpfile.js
> +gulp.task('test:windows', ['eslint', 'test:js-unit-windows']);
Remove this

2017-04-06 07:09 UTC, oderby commented on static/html/index.html
> +    <div id="root" class="layout">
I believe you need to keep the change that split this div into two divs:
```html
  <div id="root">		
     <div class="layout">
```

Otherwise you get the footer twice.

2017-04-11 17:05 UTC, schraj commented
@oderby I've added in the spanish translations provided by Eleanor from the i18N channel.  I'm still waiting on 2 new additions related to the new donate button, but I've added in some rough translations for them until we get the real ones.

2017-04-11 20:17 UTC, oderby commented
Cool. I think we're super close. @nickoneill have you had a chance to take this for a spin yet?

And finally, @nickoneill I'm inclined to say we push with the current spanish translations and then make fixes/updates to spanish copy once it's deployed and easier to get feedback on. (As opposed to requiring one of us to sit down with a Spanish speaker and run this PR/branch in front of them to get feedback before launching). Sound good?

2017-04-11 20:17 UTC, oderby approved these changes

2017-04-16 01:42 UTC, nickoneill commented
This is pretty awesome :)

I made a merge for some conflicts related to the location changes, fixed the footer for the non-js version of the page and pushed one new string: `location.changeLocation`. It's quite straightforward to change localized elements or add new ones, so this is everything we could want when it comes to supporting this. Nice work!

Definitely agree with @oderby that this should go live and then we can get improvement feedback.

2017-04-16 01:45 UTC, nickoneill commented
Actually I can't push anything that's not the conflict fix here since this is your own fork, this is the commit to add: https://github.com/5calls/5calls/commit/7096c09fe2be742e109f4fc73272aa8c091bfb49

Trying to figure out the test failure now. It's not loading the logs for me so I suspect it's just a failed test run that we get every once in a while.

2017-04-17 15:19 UTC, nickoneill commented
OK! Tests are properly running again. Text change from the merge is making a location test fail.

2017-04-19 14:47 UTC, nickoneill commented
@schraj checking in here, do you want to manually pull that commit from my branch into this so tests are running again? Then we can unblock some other work that's waiting on this and make incremental improvements here.

2017-04-19 15:35 UTC, schraj commented
Sure, I'll do that today.

2017-04-19 16:03 UTC, schraj commented
@nickoneill It looks like your "schraj-i18n" had a change to the index.html page that removed everything from the footer(which only shows up if the app can't load) except the donate button.  Did you want for this to be merged too?  It is merged currently, but I'll remove it as if/when you let me know what you wanted to do with it.

2017-04-19 16:08 UTC, nickoneill commented
Yes - there are some other changes to the footer in the FAQ PR and now that it's part of the choo page itself, there's no sense in keeping the order/links up to date in two places. It only shows if the page fails to load and well... we have bigger problems if that's the case.

2017-04-20 04:34 UTC, merged

2017-04-20 04:34 UTC, nickoneill commented
Woo!