Changed urls to remove hashes.
5calls/5calls-old pull request #256
Opened 2017-03-23 04:47 UTC by nickoneill

This change modifies the links to point to non-hash urls. I think I got all of them.

When running the client with `gulp`, this will route to appropriate urls but reloading those urls will result in 404s. I'm not sure if we can modify the gulp script for testing to do a better job here?

In production, the go backend will automatically route this links correctly, even when reloading. This change is live now and you can remove any hash from links to see the correct behavior.

2017-03-23 15:49 UTC, cdoremus requested changes
You missed the #about href in the 'Learn why calling' link on line 18 in done.js

2017-03-23 19:10 UTC, oderby commented
looks fine to me, after fixing the issue @cdoremus raised.

2017-03-23 22:52 UTC, oderby commented
Also, how does this relate to #225 ?

2017-03-24 02:56 UTC, nickoneill commented
Uh, I guess I forgot I did #225? It looks like this has a few more spots than that does, so I'll start here and add the link @cdoremus pointed out and move from `setlocation` to standard href links.

2017-03-24 16:27 UTC, greggraf commented on static/js/main.js
>        // Use Choo's internal model to control Window.location. Fixes issue #161
Since hashes are no longer used in the urls, I am wondering if it is still necessary to set the window.location here.

2017-03-24 16:31 UTC, greggraf commented
@nickoneill - maybe its too much of an edge case, and maybe this hack is too naive, but this is a possible solution for getting 404s on reload on non root url requests

Gulp development server respond with index.html to all requests #258

2017-03-24 16:49 UTC, oderby commented
@greggraf you're right, this won't be needed. I have an outstanding PR that
will need to be rebased after this lands -
https://github.com/5calls/5calls/pull/221/files#diff-93471d4bf84d0569fadcebe5fba72773L377
However, I would rather hold off on further increasing the scope of this PR
and leave fixing up history/navigation to a separate PR (the one I have
will be easy to fix up and use for that purpose).

On Fri, Mar 24, 2017 at 9:27 AM, Greg Graf <notifications@github.com> wrote:

> *@greggraf* commented on this pull request.
> ------------------------------
>
> In static/js/main.js
> <https://github.com/5calls/5calls/pull/256#discussion_r107944465>:
>
> > @@ -410,7 +410,7 @@ app.model({
>        // Use Choo's internal model to control Window.location. Fixes issue #161
>
> Since hashes are no longer used in the urls, I am wondering if it is still
> necessary to set the window.location here.
>
> —
> You are receiving this because your review was requested.
> Reply to this email directly, view it on GitHub
> <https://github.com/5calls/5calls/pull/256#pullrequestreview-28949852>,
> or mute the thread
> <https://github.com/notifications/unsubscribe-auth/ABSd9mfvm6izQQyymDQvuU0zOGg8HQPIks5ro-78gaJpZM4MmMuT>
> .
>

2017-03-25 04:33 UTC, nickoneill commented
Fixed @cdoremus! And some small href adjustments.

2017-03-25 17:20 UTC, nickoneill commented
This PR makes the core issue in #250 more prominent (breaking the page) so that should be merged before this one is pulled in.

2017-03-25 18:16 UTC, nickoneill commented
Rebased now that #250 is merged. Let me know if there are additional changes to make.

2017-03-25 19:19 UTC, oderby commented
Looks good to me!

2017-03-25 21:09 UTC, merged