Gulp development server respond with index.html to all requests
5calls/5calls-old pull request #258
Opened 2017-03-24 16:29 UTC by greggraf

added middleware to gulp task to serve index.html to all localhost:8000 requests without an extension

2017-03-25 16:24 UTC, oderby commented
@greggraf can you clarify the purpose of this PR? This change won't affect prod (we don't run gulp in prod).

2017-03-25 16:30 UTC, nickoneill commented
@oderby once we start serving real urls (not hashes) this makes reloading easier while developing.

2017-03-26 23:54 UTC, oderby requested changes
Now I see why this is helpful ;) Please rebase/merge and add the requested comment, then I think we should merge this.

2017-03-26 23:54 UTC, oderby commented on gulpfile.js
> +    if(!(path.extname(req.url))) {
Please add a comment here on why this works/is the right way to do this (it took me a bit to realize that because the SPA routes are never for files, we can check for extensions on the request to see if it's a SPA route or an actual file request)

2017-03-28 11:36 UTC, closed without merging

2017-03-28 11:49 UTC, greggraf commented on gulpfile.js
> +    if(!(path.extname(req.url))) {
@oderby - created a new branch off the latest master and a new pull request here:  #270

I hope the code comment make sense. 
https://github.com/5calls/5calls/pull/270/files#diff-b9e12334e9eafd8341a6107dd98510c9R48