Revert 0de98b5, remove zipcode lookup
5calls/5calls-old pull request #314
Opened 2017-05-15 22:02 UTC by murribu

#307

2017-05-19 03:05 UTC, oderby commented
@murribu can you provide an overview of what you've changed in the code to avoid the problem which led to #307?

2017-05-19 13:50 UTC, murribu commented
Sure!
There is only one difference between this PR and #286:
In #286 , we would attempt to establish a user's lat/lng from their zipcode in LocalStorage. If the zipcode wasn't present, we would see if their lat/lng was in LocalStorage and use that.
Now in this PR, we will just skip the first step. The LocalStorage zipcode is ignored, and if the user has their lat/lng in LocalStorage, we'll use it.
If their lat/lng is not in LocalStorage, we will not show any THP events.

We can add more methods for establishing a user's location later (like calling the Google Maps API with the user's zipcode). I just wanted to limit this pull to _fixing_ the issue at hand.

2017-05-27 23:30 UTC, oderby requested changes
The code doesn't run as is (see my comment at https://github.com/5calls/5calls/pull/314/files#diff-93471d4bf84d0569fadcebe5fba72773R273) . Also, some style cleanups and other organizational questions.

2017-05-27 23:30 UTC, oderby commented on static/js/components/townHall.js
> +  if (linkExists){
Not sure this does anything to improve the legibility of the code over just `if (e.link) {` Since the if is only concerned with truthiness of a value, the double negation is not needed when used this way.

2017-05-27 23:30 UTC, oderby commented on static/js/components/townHall.js
> +  if (notesExist){
Same comment as above.

2017-05-27 23:30 UTC, oderby commented on static/js/components/townHall.js
> +    ret.innerHTML = e.Notes;
In general, this would be flagged as making our site vulnerable to XSS attacks - how much do we trust the content pulled from THP? Also, maybe it's not a huge deal, since we don't have any secure content/cookies on the client/browser.

That said, if there's a way we can do this safely, we should do it that way.

2017-05-27 23:30 UTC, oderby commented on static/js/components/townHall_test.js
> +const localEvents = [{
Can we pull this out to a separate file, townHall_test_data.json or such? Just to cleanup this file a bit.

2017-05-27 23:30 UTC, oderby commented on static/js/main.js
> +      let divisions = townHallUtils.parseCivicData(response.divisions);
this can be `const`

2017-05-27 23:30 UTC, oderby commented on static/js/components/townHall.js
> +  if (state.localEvents && state.localEvents.length > 0){
nit: here and elsewhere, please insert a space between the `if` condidtion and open bracket. That is, style should be `if (foo === true) {`

2017-05-27 23:30 UTC, oderby commented on static/js/main.js
> +      }else{
style nit: to be consistent with spacing in rest of document, use `} else {`

2017-05-27 23:30 UTC, oderby commented on static/js/main.js
> +      }else{
style nit: use `} else {` to be consistent with spacing in rest of doc.

2017-05-27 23:30 UTC, oderby commented on static/js/main.js
> +        lng = geo.split(",")[1];
Should probably protect here against the result of `geo.split` returning a length 1 array (will only happen if the cached geo location is borked, but could definitely happen). Or better yet, only use it if it's a length==2 array (anything else is malformed/wrong data type).

2017-05-27 23:30 UTC, oderby commented on static/js/main.js
> +    localEvents: {},
`localEvents` appears to be an array, not an object. Should therefore be initialized to an empty array.

2017-05-27 23:30 UTC, oderby commented on static/js/utils/townHallUtils.js
> +  stateAbbrs: stateAbbrs,
I don't see anything using this...what's the reason to export it?

2017-05-27 23:30 UTC, oderby commented on static/js/utils/townHallUtils.js
> +  for( var prop in obj ) {
Just use `Object.keys` method, and then you can avoid the check on the following line entirely.

2017-05-27 23:30 UTC, oderby commented on static/js/main.js
> +        events = townHallUtils.filterForLocalEvents(events, state.divisions, lat, lng);
When I run this code, I'm seeing the events data returned from THP endpoint is a JSON object, but `filterForLocalEvents` expects the `events` input to be an array.

2017-06-07 20:52 UTC, murribu commented
I believe most of these issues have now been addressed. The exception is the XSS vulnerability. Perhaps we should have a backend endpoint to call which retrieves the THP data, sanitizes it, and returns it to the frontend?

2017-06-07 21:53 UTC, murribu commented on static/js/utils/townHallUtils.js
> +  for( var prop in obj ) {
CI yelled at me for using Object.keys. I guess IE doesn't like it.

2017-06-08 15:25 UTC, oderby commented on static/js/components/townHall_test_data.json
> +  "dateObj": (new Date()).getTime() + 100000, // make sure it's in the future
Oh, I didn't realize there was actual javascript code executed. This should actually be a js file then...

2017-06-08 15:25 UTC, oderby commented on static/js/utils/townHallUtils.js
> +  for( var prop in obj ) {
Yes, `Object.values` is not yet a fully supported operator. `Object.keys` should be fine to use though. Is there a reason you tried using `Object.values` below?

2017-06-08 20:21 UTC, murribu commented on static/js/utils/townHallUtils.js
> +  for( var prop in obj ) {
I got confused. I thought Object.keys wasn't supported and Object.values was supported. I figured Object.values would be a more straight-forward method of finding the stateAb than getKeyByValue. Since Object.keys is supported, I'm using that now.

2017-06-09 21:48 UTC, oderby requested changes
Looking good. Just one important thing to address (returning consistently ordered events) and a minor copy suggestion to consider. Then lgtm.

2017-06-09 21:48 UTC, oderby commented on static/js/main.js
> +          localEvents: eventsArr.slice(0,3)
I think we should return the 3 closest events both in terms of location *and time* - right now, if there are more than 3 upcoming events at the same location, we just return a random 3 - I'd want to see the 3 upcoming ones.

2017-06-09 21:48 UTC, oderby commented on static/locales/en.json
> +      "thpCredit": "Events from the <a href='https://townhallproject.com' target='_new'>Town Hall Project</a>"
nit: I think it'd make sense to indicate that more information/events can be seen by going to the THP. Perhaps something like "These events and more information provided by the Town Hall Project"

2017-06-14 13:50 UTC, murribu commented on static/js/main.js
> +          localEvents: eventsArr.slice(0,3)
Check out [townHallUtils.sortEvents](https://github.com/5calls/5calls/pull/314/files#diff-2b1285f6251ee2934b30977d2a72d8dbR149). It sorts events by distance - and if the distance is the same, it then sorts by date. So, I think this request is already addressed. Let me know if I'm misunderstanding the request.

2017-06-14 13:55 UTC, murribu commented on static/locales/en.json
> +      "thpCredit": "Events from the <a href='https://townhallproject.com' target='_new'>Town Hall Project</a>"
It would be fine with me to change this, but I'd like to also change the es.json accordingly. Shall I post it to the i18n slack channel?

2017-06-14 20:04 UTC, oderby commented on static/js/main.js
> +          localEvents: eventsArr.slice(0,3)
Per conversation on slack, I think we should keep this sorting logic as is and revisit it after we get feedback/see uptake of feature.

2017-06-14 20:04 UTC, oderby commented on static/locales/en.json
> +      "thpCredit": "Events from the <a href='https://townhallproject.com' target='_new'>Town Hall Project</a>"
As discussed on slack, leaving copy as is for this initial version.

2017-06-15 15:35 UTC, murribu commented
So, is this ready to go?

2017-06-15 15:37 UTC, oderby approved these changes

2017-06-15 15:39 UTC, merged

2017-06-15 15:49 UTC, nickoneill commented
Awesome!