Added support for non-contact action items
5calls/5calls-old pull request #361
Opened 2017-11-17 01:41 UTC by nickoneill

Requested from one of our early teams, easy enough to test out.

Reworks outcome sending to be entirely the new `FlexibleOutcome` from the fetch contact type, no more enums :(

2017-11-17 01:44 UTC, nickoneill commented
Example is `team/nick/32`

2017-11-20 17:35 UTC, cdoremus requested changes
@nickoneill for the record, this is a summary of my recommendations I discussed with you on Slack last night:

I've done some experimenting with the PR and it appears that you can use `OutcomeData` instead of `FlexibleOutcomeData`, by having the `outcome` field of this type: `UserContactEventType | string` This allows you to use code completion if you want the old outcomes or add a custom outcome as a string. In either case, a string is passed to the back end as the outcome value.

You don't need that switch statement in `Outcomes.dispatchOutcome()` that you removed in the PR. You can also remove `FlexibleOutcomeData` and replace all references to it with `OutcomeData`.

To keep things cleaner, I would create a new type:
```
type UserOutcomeResult =  UserContactEventType | string;
```

The call signature of dispatchOutcome becomes
```
  dispatchOutcome(e: React.MouseEvent<HTMLButtonElement>,
                  outcome: UserOutcomeResult = UserContactEventType.SKIP) 
```

You'll also need to change `UserContactEvent.result` to be of type `UserOutcomeResult`.

2017-11-20 17:41 UTC, nickoneill commented
Thanks! This'll make things much simpler.

2017-11-21 02:07 UTC, cdoremus commented on src/components/call/IssueLink.tsx
>        <h4 className="call__script__link"><a target="link" href={issue.link}>{linkTitle}</a></h4>
If the `issue` prop is optional (as defined on line 5),  `issue.link` will throw a `ReferenceError` here when it is `undefined`.

2017-11-21 02:27 UTC, nickoneill commented on src/components/call/IssueLink.tsx
>        <h4 className="call__script__link"><a target="link" href={issue.link}>{linkTitle}</a></h4>
Not in this case, it will fail at `issue` first and won't continue to evaluate the cases. Otherwise this would fail when you reload a page from scratch in dev (there's initially no currentIssue and the page has to search the downloaded issues for something that matches the path)

2017-11-21 04:18 UTC, cdoremus approved these changes
Good to go. Nice job!
Onward and upward!!

2017-11-21 04:19 UTC, merged