Added a query param to force the location.
5calls/5calls-old pull request #362
Opened 2017-11-20 19:34 UTC by nickoneill

This is coming in handy with automating something I'm working on, but could also be used to send people to the right districts if they're split and don't know how to fix.

2017-11-21 03:07 UTC, cdoremus requested changes
As stated inline, locationState needs to be updated to dispatch an Action to a Redux reducer via an action creator.

2017-11-21 03:07 UTC, cdoremus commented on src/redux/remoteData/asyncActionCreator.ts
> +          state.locationState.address = pair[1];
State always needs to be updated by using a Redux reducer via an Action created by an ActionCreator.

2017-11-21 18:27 UTC, nickoneill commented on src/redux/remoteData/asyncActionCreator.ts
> +          state.locationState.address = pair[1];
It didn't look like `setState` is available here. How would I go about getting that in this context?

2017-11-21 19:24 UTC, cdoremus commented on src/redux/remoteData/asyncActionCreator.ts
> +          state.locationState.address = pair[1];
Use the dispatch function to call the appropriate action creator.

2017-11-21 19:25 UTC, nickoneill commented on src/redux/remoteData/asyncActionCreator.ts
> +          state.locationState.address = pair[1];
Ohhhh right

2017-11-23 01:59 UTC, nickoneill commented
OK! Thanks for pointing that out, makes total sense.

2017-11-23 02:20 UTC, cdoremus approved these changes
Thanks for making the changes.

2017-11-23 02:20 UTC, merged