Opening PR for WIP
5calls/5calls-old pull request #416
Opened 2018-08-13 15:40 UTC by nabrahamson

Implement context api for groups

THIS CURRENTLY DOES NOT RUN
There is a dependency conflict with 5-calls/react-components

2018-08-24 22:20 UTC, nickoneill reviewed
Some general questions

2018-08-24 22:20 UTC, nickoneill commented on package.json
> +    "@types/redux": "^3.6.0",
Anything under @types should be dev dependencies only

2018-08-24 22:20 UTC, nickoneill commented on src/common/model.ts
> +  static from(groupState: GroupState) {
Does this make sense here? Or on `GroupState`?

2018-08-24 22:20 UTC, nickoneill commented on src/components/layout/Header.tsx
> +    } else {
Having an empty profile isn't the same as the profile being undefined. Do we check this up the stack or something?

2018-08-24 22:20 UTC, nickoneill commented on src/contexts/RemoteStateContext.ts
> +export interface ProviderState {
If this is the `RemoteStateContext` doesn't that mean the interface should be `RemoteState` rather than `ProviderState`?

2018-08-24 22:20 UTC, nickoneill commented on src/redux/group/asyncActionCreator.ts
> +      dispatch<any>(cacheGroup(group.groupID));
Does dispatch complain without a type here? I don't think I have to do the same in 5calls-action.

2018-09-07 15:56 UTC, nabrahamson commented on src/common/model.ts
> +  static from(groupState: GroupState) {
I think this makes more sense here as it's creating a Group object from a GroupState interface. I believe putting it on GroupState would require us to convert GroupState to a class.

2018-09-07 16:40 UTC, nabrahamson commented on src/components/layout/Header.tsx
> +    } else {
I think this is related to the current login issues we've talked about over Slack. Looking at the react-components repo, the userProfile param is defined as optional, so I shouldn't need to pass in an empty profile.

2018-09-07 16:44 UTC, nickoneill commented on src/components/layout/Header.tsx
> +    } else {
Agreed. Do you recall why you needed the empty profile here when this change was made?

2018-09-07 16:54 UTC, nabrahamson commented on src/components/layout/Header.tsx
> +    } else {
Figured out the login error but I need to figure out why it occurred. For some reason when I pull down the react-components repo, the typings defininition for the CustomLogin component isn't defining the userProfile prop as optional. If I go into the node modules folder and edit the typings definition for the component, I can get rid of the empty profile and things work as expected.

2018-09-07 16:59 UTC, nabrahamson commented on src/components/layout/Header.tsx
> +    } else {
Building the current version of react-components on my machine gives the correct typings definition for this component. This block of code will be reverted in my next push.

2018-09-07 17:38 UTC, nabrahamson commented
To reply to the comment about Calls.tsx. I changed it to slug because the dictionary contactIndexes was keyed on issue slugs. I can change the logic so that it will look for the id first, then the slug in case the id returns undefined.

2018-09-07 17:53 UTC, nickoneill commented on src/common/constants.ts
> +export const PAGETITLE = '5 Calls: Make your voice heard';
Did you add this with the intent of using it somewhere? Search doesn't bring it up elsewhere on this page.

2018-09-07 17:54 UTC, nickoneill commented on src/common/model.ts
> +  static from(groupState: GroupState) {
OK, fair enough

2018-09-07 17:56 UTC, nickoneill commented on src/components/AppProvider.tsx
> +  store: Store<any>;
I believe this can be `Store<ApplicationState>` now that everything is in

2018-09-07 17:59 UTC, nickoneill commented on src/components/NotFoundPage.tsx
> +      <Footer/>
How does this work now that t isn't sent to footer and to navigation below that? Navigation is using `props.t` to translate stuff, and it appears correctly. I'm not 100% on where that comes from since we removed it from the props passed to the footer.

2018-09-07 18:15 UTC, nickoneill requested changes
Looks like groups aren't loading - or they are loading but not displaying?

I noted a bunch of the translation `<any>` instances. There are a few that don't have this and aren't asking for it, so there should be a simple way to remove these.

We can leave the `dispatch<any>` in for now, I think we'll end up refactoring the dispatch calls out at a later time so don't worry about that for now.

Final thing is to make sure the tests are working again.

2018-09-07 18:15 UTC, nickoneill commented on src/components/call/ContactDetails.tsx
> +  readonly t: TranslationFunction|any;
Let's remove this `any`

2018-09-07 18:15 UTC, nickoneill commented on src/components/call/ContactOffices.tsx
> +  readonly t: TranslationFunction|any;
Remove this `any`

2018-09-07 18:15 UTC, nickoneill commented on src/components/call/NoContactSplitDistrict.tsx
> +  readonly t: TranslationFunction|any;
Remove `any`

2018-09-07 18:15 UTC, nickoneill commented on src/components/call/Outcomes.tsx
> +  readonly t: TranslationFunction|any;
`any`

2018-09-07 18:15 UTC, nickoneill commented on src/components/call/Script.tsx
> +  readonly t: TranslationFunction|any;
`any`

2018-09-07 18:15 UTC, nickoneill commented on src/components/done/DonePage.tsx
> +interface RouteProps {}
If route props is nothing, then remove it and don't inherit in `Props`

2018-09-07 18:15 UTC, nickoneill commented on src/components/groups/GroupPage.tsx
> +// tslint:disable-next-line:no-bitwise
What's this about?

2018-09-07 18:15 UTC, nickoneill commented on src/components/issues/MoreIssues.tsx
> +  readonly t: TranslationFunction|any;
`any`

2018-09-07 18:15 UTC, nickoneill commented on src/components/shared/Promotion.tsx
> +  readonly t: TranslationFunction|any;
`any`

2018-09-10 16:05 UTC, nabrahamson commented on src/components/NotFoundPage.tsx
> +      <Footer/>
I missed the translation in the footer component. It should be removed. The navigation component will be importing the i18next object and calling the translation function off of that like the other components are doing now. My next pushed changes will reflect this.

2018-09-10 19:04 UTC, nabrahamson commented on src/components/done/DonePage.tsx
> +interface RouteProps {}
In order for RouteComponentProps to be extended, a type needs to be included. You'll see that RouteProps has been removed, but and empty object is being passed into the type parameter of RouteComponentProps now.

2018-09-10 19:07 UTC, nabrahamson commented on src/common/constants.ts
> +export const PAGETITLE = '5 Calls: Make your voice heard';
That was my intent. I'll remove this constant as I've found that there are many places where static strings are embedded in code.

2018-09-10 21:50 UTC, nickoneill commented
Groups load now, but the sidebar doesn't reflect the current team or the use of custom issues if the team has them.

See the difference between https://5calls.org/team/nick and http://localhost:3000/team/nick

2018-09-10 22:11 UTC, nabrahamson commented
The problem with the sidebar was that the currentGroup wasn't being passed into the sidebarHeader. Should be working properly now.

2018-09-11 17:50 UTC, nickoneill commented
Sidebar is working great for groups!

2018-09-11 18:00 UTC, nickoneill commented
OK one other issue: if you navigate to a group page with custom issues, then click the header to get back home, the sidebar (header & issues) don't revert back to the main ones

2018-09-11 20:15 UTC, nabrahamson commented
I've added a prop to the layout page that specifies if group issues should
be shown in the sidebar or not. I've tested this on both the team/group and
team/group/issue pages.

On Tue, Sep 11, 2018 at 1:00 PM nickoneill <notifications@github.com> wrote:

> OK one other issue: if you navigate to a group page with custom issues,
> then click the header to get back home, the sidebar (header & issues) don't
> revert back to the main ones
>
> —
> You are receiving this because you were assigned.
> Reply to this email directly, view it on GitHub
> <https://github.com/5calls/5calls/pull/416#issuecomment-420364870>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/AHH62kj-YR3u1K1OvQANChwhY1b9Qo8oks5uZ_pQgaJpZM4V6vvu>
> .
>

2018-09-11 21:08 UTC, nickoneill commented
Looks good!

2018-09-11 21:09 UTC, nickoneill approved these changes
👍

2018-09-11 21:11 UTC, merged