Profile Page
5calls/5calls-old pull request #418
Opened 2018-08-30 23:34 UTC by nickoneill

Using the new profile API endpoint, we're able to display details of calls from the last 30 days along with total call stats. A solid starting point.

Use along with the `5calls-api` profile PR changes until it's merged.

Also removes onesignal, I don't think it's more useful than SMS for reminders on web.

2018-08-31 00:47 UTC, nabrahamson commented on src/components/profile/ProfilePage.tsx
> +        // console.log('error getting profile', error);
At some point we should be using an actual logger instead of letting things fail invisibly. Either storing things in a text based error log, or logging them to the database. (Preferrably the former than the latter).

2018-08-31 00:50 UTC, nickoneill commented on src/components/profile/ProfilePage.tsx
> +        // console.log('error getting profile', error);
Open to this. Can we manually log things to sentry? We already do automatic JS error catching there.

2018-08-31 00:53 UTC, nabrahamson requested changes

2018-08-31 00:53 UTC, nabrahamson commented on src/redux/remoteData/asyncActionCreator.ts
> +import { getAllIssues, getGroupIssues, getCountData,
For purposes of making code reviews easier to see what's been added/removed from a list of imports, when importing multiple objects, they should be one per line like 

```
import {
  getAllIssues,
  getGroupIssues,
  getCountData, 
  ...
} from 'packageName';

2018-08-31 00:55 UTC, nabrahamson commented on src/components/profile/ProfilePage.tsx
> +        // console.log('error getting profile', error);
I will have to look into this as I'm not as familiar with sentry as I should be.

2018-08-31 01:17 UTC, nickoneill commented on src/redux/remoteData/asyncActionCreator.ts
> +import { getAllIssues, getGroupIssues, getCountData,
I'll look to see if this is a tslint option

2018-09-02 22:15 UTC, nickoneill commented on src/redux/remoteData/asyncActionCreator.ts
> +import { getAllIssues, getGroupIssues, getCountData,
I'm actually not as much of a fan of this as I thought I would be. Doing this for every import makes for excessive numbers of lines that you have to scroll through before you reach actual code. There isn't an easy tslint for managing this style either.

A proposal for this: for imports that would extend beyond the line length limit, use the each-line style. Otherwise, use the normal style. I've updated the imports on this page to reflect this, but part of the problem here is that this file is really excessive. Too much stuff going on in one location.

2018-09-03 21:20 UTC, nabrahamson approved these changes

2018-09-05 01:02 UTC, merged