Added a midterm challenge page
5calls/5calls-old pull request #423
Opened 2018-09-17 17:02 UTC by nickoneill

Not much excitement here. New midterm challenge landing page, and home design to go along with it. Small API endpoint to get midterm challenge numbers from the API too.

Notably: using an event emitter to communicate across components via a event context. It would be nice to have some stronger types around this, I may look into something that is more typescript-focused rather than stringly-typed events names.

2018-09-17 18:17 UTC, nabrahamson commented
When pulling down the updated npm packages, I get a message stating that 5calls/react-components does not have a version available at 0.0.14

2018-09-17 22:41 UTC, nickoneill commented
OK, you should be good to go on this. I hate micro versioning components for minor changes.

2018-09-18 15:51 UTC, nabrahamson commented
@nickoneill Everything runs well after updating react-components. Looking at the event emitter pattern, This seems like a straight forward way to pass the events around in a DRY way with minimal code.

2018-09-18 15:51 UTC, nabrahamson requested changes

2018-09-18 15:51 UTC, nabrahamson commented on src/components/MidtermsPage.tsx
> +
Did you mean to have weeks 5-8 included in this as well?

2018-09-18 16:00 UTC, nickoneill commented on src/components/MidtermsPage.tsx
> +
Yeah, they're revealed over time though. I'll add the rest of them in today with another small change I want to make.

2018-09-20 00:12 UTC, nickoneill commented
Fixed these items, merging in.

2018-09-20 00:14 UTC, merged